### ISSUE TITLE
www-client/ungoogled-chromium-97.0.4692.71-r1 needs dev-python/html5lib

### ISSUE THREAD

**Issue by logrusx** [PF4Public/gentoo-overlay#123]
After manually emerging dev-python/html5lib the following build issue was resolved:

[8355/22215] python3.9 ../../third_party/catapult/tracing/bin/generate_about_tracing_contents --outdir gen/content/browser/tracing
FAILED: gen/content/browser/tracing/about_tracing.js gen/content/browser/tracing/about_tracing.html 
python3.9 ../../third_party/catapult/tracing/bin/generate_about_tracing_contents --outdir gen/content/browser/tracing
Traceback (most recent call last):
  File "/var/tmp/portage/www-client/ungoogled-chromium-97.0.4692.71-r1/work/chromium-97.0.4692.71/third_party/catapult/common/py_vulcanize/py_vulcanize/html_module.py", line 28, in Parse
    parser_results = parse_html_deps.HTMLModuleParser().Parse(self.contents)
  File "/var/tmp/portage/www-client/ungoogled-chromium-97.0.4692.71-r1/work/chromium-97.0.4692.71/third_party/catapult/common/py_vulcanize/py_vulcanize/parse_html_deps.py", line 304, in Parse
    return HTMLModuleParserResults(html)
  File "/var/tmp/portage/www-client/ungoogled-chromium-97.0.4692.71-r1/work/chromium-97.0.4692.71/third_party/catapult/common/py_vulcanize/py_vulcanize/parse_html_deps.py", line 170, in __init__
    self._soup = bs4.BeautifulSoup(html, 'html5lib')
  File "/var/tmp/portage/www-client/ungoogled-chromium-97.0.4692.71-r1/work/chromium-97.0.4692.71/third_party/catapult/third_party/beautifulsoup4-4.9.3/py3k/bs4/__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?

Regards,
Georgi

**Comment by PF4Public** [comment]
Your USE flags and the full build log?

**Comment by logrusx** [comment]
[ebuild   R   ~] www-client/ungoogled-chromium-97.0.4692.71-r1::pf4public  USE="clang convert-dict hangouts js-type-check official optimize-thinlto optimize-webui partition proprietary-codecs pulseaudio screencast system-harfbuzz system-libevent system-openh264 system-re2 thinlto vaapi wayland -cfi -cups -custom-cflags -debug -enable-driver -headless -kerberos -pgo (-selinux) -suid -system-ffmpeg -system-icu -system-jsoncpp -system-libvpx -system-openjpeg -tcmalloc -vdpau -widevine"

L10N only contains bg.

I'm missing the build log, as I resumed the build and it overwrote it. I'll try to produce one, but it's going to take some time.

Regards,
Georgi

**Comment by logrusx** [comment]
I'm closing this issue as until the time I can reproduce it, it might as well become irrelevant and I run out of time with the computer I got it first for now. If I hit it again, I'll take care to preserve the build log this time.

Regards,
Georgi
