### ISSUE TITLE
dev-util/electron-18.3.1: No such file or directory: 'npm'

### ISSUE THREAD

**Issue by reagentoo** [PF4Public/gentoo-overlay#154]
### Config

```
# emerge -pv nodejs electron

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R    ] net-libs/nodejs-18.1.0:0/18::gentoo  USE="icu inspector snapshot ssl system-icu system-ssl -debug -doc -lto -npm -pax-kernel -systemtap -test" CPU_FLAGS_X86="sse2" 0 KiB
[ebuild  N     ] dev-util/electron-18.3.1:18/3.1::staging  USE="clang gtk4 proprietary-codecs pulseaudio system-ffmpeg system-harfbuzz system-icu system-jsoncpp system-libevent system-libusb system-openh264 system-png system-re2 system-snappy vaapi wayland -cups -custom-cflags -debug -hangouts -js-type-check -kerberos -optimize-thinlto -optimize-webui -pgo (-selinux) -system-libvpx -system-openjpeg -thinlto -ungoogled -vdpau" L10N="ru -am -ar -bg -bn -ca -cs -da -de -el -en-GB -es -es-419 -et -fa -fi -fil -fr -gu -he -hi -hr -hu -id -it -ja -kn -ko -lt -lv -ml -mr -ms -nb -nl -pl -pt-BR -pt-PT -ro -sk -sl -sr -sv -sw -ta -te -th -tr -uk -vi -zh-CN -zh-TW" 0 KiB
```

### Log

<details>
<summary>FileNotFoundError: [Errno 2] No such file or directory: 'npm'</summary>
<p>

```
[2199/14435] python3.9 ../../electron/build/npm-run.py --silent pre-flight -- --stamp /var/tmp/portage/dev-util/electron-18.3.1/work/chromium-100.0.4896.127/out/Release/gen/electron/npm_pre_stamps/npm_pre_flight_build_electron_definitions.stamp
FAILED: gen/electron/npm_pre_stamps/npm_pre_flight_build_electron_definitions.stamp 
python3.9 ../../electron/build/npm-run.py --silent pre-flight -- --stamp /var/tmp/portage/dev-util/electron-18.3.1/work/chromium-100.0.4896.127/out/Release/gen/electron/npm_pre_stamps/npm_pre_flight_build_electron_definitions.stamp
Traceback (most recent call last):
  File "/var/tmp/portage/dev-util/electron-18.3.1/work/chromium-100.0.4896.127/out/Release/../../electron/build/npm-run.py", line 16, in <module>
    subprocess.check_output(args, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'npm'
[2200/14435] python3.9 ../../electron/build/npm-run.py --silent pre-flight -- --stamp /var/tmp/portage/dev-util/electron-18.3.1/work/chromium-100.0.4896.127/out/Release/gen/electron/npm_pre_stamps/npm_pre_flight_default_app_js.stamp
FAILED: gen/electron/npm_pre_stamps/npm_pre_flight_default_app_js.stamp 
python3.9 ../../electron/build/npm-run.py --silent pre-flight -- --stamp /var/tmp/portage/dev-util/electron-18.3.1/work/chromium-100.0.4896.127/out/Release/gen/electron/npm_pre_stamps/npm_pre_flight_default_app_js.stamp
Traceback (most recent call last):
  File "/var/tmp/portage/dev-util/electron-18.3.1/work/chromium-100.0.4896.127/out/Release/../../electron/build/npm-run.py", line 16, in <module>
    subprocess.check_output(args, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'npm'
```

</p>
</details>

**Comment by PF4Public** [comment]
What is `::staging`?

**Comment by PF4Public** [comment]
Please also note that `gtk4` might fail: #143

**Comment by reagentoo** [comment]
> `-npm`

Don't worry about the lack of `net-libs/nodejs[npm]` in BDEPEND?

**Comment by PF4Public** [comment]
> Don't worry about the lack of `net-libs/nodejs[npm]` in BDEPEND?

What do you mean by that?

**Comment by reagentoo** [comment]
https://github.com/PF4Public/gentoo-overlay/blob/f1f8622e5af0694de4e150b987bf65cbf179e6b6/dev-util/electron/electron-18.3.1.ebuild#L1288
```
-	>=net-libs/nodejs-7.6.0[inspector]
+	>=net-libs/nodejs-7.6.0[inspector,npm]
```

**Comment by reagentoo** [comment]
It is quite obvious that a flag is missing in the dependencies. But of course you can do nothing. And so normal. :)
