### ISSUE TITLE
net-im/element-desktop: fails to compile (with USE="-build-online")

### ISSUE THREAD

**Issue by stikonas** [PF4Public/gentoo-overlay#171]
```
[32m * [39;49;00mPackage:    net-im/element-desktop-1.11.5:0
[32m * [39;49;00mRepository: pf4public
[32m * [39;49;00mMaintainer: PF4Public@users.noreply.github.com
[32m * [39;49;00mUSE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
[32m * [39;49;00mFEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
 [32m*[0m Checking whether python3_10 is suitable ...
 [32m*[0m   >=dev-lang/python-3.10.4:3.10 ...
[A[201C [34;01m[ [32;01mok[34;01m ][0m
 [32m*[0m Using python3.10 to build (via PYTHON_COMPAT iteration)
>>> Unpacking source...
>>> Unpacking element-desktop-1.11.5.tar.gz to /var/tmp/portage/net-im/element-desktop-1.11.5/work
>>> Source unpacked in /var/tmp/portage/net-im/element-desktop-1.11.5/work
>>> Preparing source in /var/tmp/portage/net-im/element-desktop-1.11.5/work/element-desktop-1.11.5 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/net-im/element-desktop-1.11.5/work/element-desktop-1.11.5 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/net-im/element-desktop-1.11.5/work/element-desktop-1.11.5 ...
[2K[1G[1myarn config v1.22.19[22m
[2K[1G[32msuccess[39m Set "disable-self-update-check" to "true".
[2K[1GDone in 1.30s.
[2K[1G[1myarn config v1.22.19[22m
[2K[1G[32msuccess[39m Set "nodedir" to "/usr/include/electron-19/node".
[2K[1GDone in 0.10s.
[2K[1G[1myarn config v1.22.19[22m
[2K[1G[32msuccess[39m Set "ignore-engines" to "true".
[2K[1GDone in 1.05s.
[2K[1G[1myarn config v1.22.19[22m
[2K[1G[32msuccess[39m Set "yarn-offline-mirror" to "/var/tmp/portage/net-im/element-desktop-1.11.5/distdir".
[2K[1GDone in 0.09s.
 [32m*[0m Installing node_modules
[2K[1G[1myarn install v1.22.19[22m
[2K[1G[2m[1/4][22m Resolving packages...
[1G[0K[2K[1G[33mwarning[39m Resolution field "@types/node@16.11.38" is incompatible with requested version "@types/node@^17.0.36"
[2K[1G[33mwarning[39m Resolution field "@types/node@16.11.38" is incompatible with requested version "@types/node@16.9.1"
[2K[1G[2K[1G[2m[2/4][22m Fetching packages...
[2K[1G[2m[3/4][22m Linking dependencies...
[2K[1G[33mwarning[39m " > eslint-plugin-matrix-org@0.4.0" has unmet peer dependency "eslint-plugin-jsx-a11y@^6.5.1".
[2K[1G[2m[4/4][22m Building fresh packages...
[2K[1G[31merror[39m /var/tmp/portage/net-im/element-desktop-1.11.5/work/element-desktop-1.11.5/node_modules/playwright: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /var/tmp/portage/net-im/element-desktop-1.11.5/work/element-desktop-1.11.5/node_modules/playwright
Output:
BEWARE: your OS is not officially supported by Playwright; downloading fallback build.
Downloading Chromium 105.0.5195.19 (playwright build v1019)...
Downloading Chromium 105.0.5195.19 (playwright build v1019)...
Downloading Chromium 105.0.5195.19 (playwright build v1019)...
/var/tmp/portage/net-im/element-desktop-1.11.5/work/element-desktop-1.11.5/node_modules/playwright-core/lib/server/registry/index.js:683
      throw new Error(`Failed to download ${title}, caused by\n${e.stack}`);
            ^

Error: Failed to download Chromium 105.0.5195.19 (playwright build v1019), caused by
Error: getaddrinfo EAI_AGAIN playwright-verizon.azureedge.net
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
    at /var/tmp/portage/net-im/element-desktop-1.11.5/work/element-desktop-1.11.5/node_modules/playwright-core/lib/server/registry/index.js:683:13
    at async Registry._downloadExecutable (/var/tmp/portage/net-im/element-desktop-1.11.5/work/element-desktop-1.11.5/node_modules/playwright-core/lib/server/registry/index.js:682:5)
    at async Registry.install (/var/tmp/portage/net-im/element-desktop-1.11.5/work/element-desktop-1.11.5/node_modules/playwright-core/lib/server/registry/index.js:656:9)
    at async installBrowsersForNpmInstall (/var/tmp/portage/net-im/element-desktop-1.11.5/work/element-desktop-1.11.5/node_modules/playwright-core/lib/server/registry/index.js:850:3)
[2K[1G[34minfo[39m Visit [1mhttps://yarnpkg.com/en/docs/cli/install[22m for documentation about this command.
 [31;01m*[0m ERROR: net-im/element-desktop-1.11.5::pf4public failed (compile phase):
 [31;01m*[0m   (no error message)
 [31;01m*[0m 
 [31;01m*[0m Call stack:
 [31;01m*[0m     ebuild.sh, line 122:  Called src_compile
 [31;01m*[0m   environment, line 4177:  Called die
 [31;01m*[0m The specific snippet of code:
 [31;01m*[0m       node /usr/bin/yarn install ${ONLINE_OFFLINE} --no-progress || die;
 [31;01m*[0m 
 [31;01m*[0m If you need support, post the output of `emerge --info '=net-im/element-desktop-1.11.5::pf4public'`,
 [31;01m*[0m the complete build log and the output of `emerge -pqv '=net-im/element-desktop-1.11.5::pf4public'`.
 [31;01m*[0m The complete build log is located at '/var/tmp/portage/net-im/element-desktop-1.11.5/temp/build.log'.
 [31;01m*[0m The ebuild environment file is located at '/var/tmp/portage/net-im/element-desktop-1.11.5/temp/environment'.
 [31;01m*[0m Working directory: '/var/tmp/portage/net-im/element-desktop-1.11.5/work/element-desktop-1.11.5'
 [31;01m*[0m S: '/var/tmp/portage/net-im/element-desktop-1.11.5/work/element-desktop-1.11.5'

```

**Comment by PF4Public** [comment]
Even though I usually do a [thorough check](https://github.com/PF4Public/gentoo-overlay/actions/runs/3045045733) before stabilizing ebuilds, this might've slipped through due to limited sandbox functionality on GitHub runners. Sorry.

**Comment by stikonas** [comment]
> Even though I usually do a [thorough check](https://github.com/PF4Public/gentoo-overlay/actions/runs/3045045733) before stabilizing ebuilds, this might've slipped through due to limited sandbox functionality on GitHub runners. Sorry.

No problem. That's exactly what bug reports are for. (And probably my own overlay is even worse in terms of compile errors.)

Thanks for fixing this!
