### ISSUE TITLE
app-editor/vscode-1.79.2: bad export type for `tree_sitter_tsx_external_scanner_create`: undefined

### ISSUE THREAD

**Issue by nethershaw** [PF4Public/gentoo-overlay#239]
I have not been able to find a combination of vscode ebuilds from this overlay and electron versions that will allow vscode to successfully build since `app-editors/vscode-1.77.3` with `dev-util/electron-20.3.12-r1`. All vscode ebuilds since then bail with a similar error:

```js
>>> Compiling source in /var/tmp/portage/app-editors/vscode-1.79.2/work/vscode-1.79.2 ...
...
[16:08:54] Starting compilation api-proposal-names...
Assertion failed: bad export type for `tree_sitter_tsx_external_scanner_create`: undefined
Unhandled Rejection at: Promise Promise {
  <rejected> RuntimeError: abort(Assertion failed: bad export type for `tree_sitter_tsx_external_scanner_create`: undefined). Build with -s ASSERTIONS=1 for more info.
      at se (/var/tmp/portage/app-editors/vscode-1.79.2/work/vscode-1.79.2/node_modules/web-tree-sitter/tree-sitter.js:1:6761) 
      at k (/var/tmp/portage/app-editors/vscode-1.79.2/work/vscode-1.79.2/node_modules/web-tree-sitter/tree-sitter.js:1:4462) 
      at Pe (/var/tmp/portage/app-editors/vscode-1.79.2/work/vscode-1.79.2/node_modules/web-tree-sitter/tree-sitter.js:1:12582) 
      at c (/var/tmp/portage/app-editors/vscode-1.79.2/work/vscode-1.79.2/node_modules/web-tree-sitter/tree-sitter.js:1:10613)
      at /var/tmp/portage/app-editors/vscode-1.79.2/work/vscode-1.79.2/node_modules/web-tree-sitter/tree-sitter.js:1:10879 
      at async /var/tmp/portage/app-editors/vscode-1.79.2/work/vscode-1.79.2/node_modules/@vscode/l10n-dev/dist/main.js:254:10
      at async /var/tmp/portage/app-editors/vscode-1.79.2/work/vscode-1.79.2/node_modules/@vscode/l10n-dev/dist/main.js:243:22
} reason: RuntimeError: abort(Assertion failed: bad export type for `tree_sitter_tsx_external_scanner_create`: undefined). Build with -s ASSERTIONS=1 for more info.
    at se (/var/tmp/portage/app-editors/vscode-1.79.2/work/vscode-1.79.2/node_modules/web-tree-sitter/tree-sitter.js:1:6761)
    at k (/var/tmp/portage/app-editors/vscode-1.79.2/work/vscode-1.79.2/node_modules/web-tree-sitter/tree-sitter.js:1:4462)
    at Pe (/var/tmp/portage/app-editors/vscode-1.79.2/work/vscode-1.79.2/node_modules/web-tree-sitter/tree-sitter.js:1:12582)
    at c (/var/tmp/portage/app-editors/vscode-1.79.2/work/vscode-1.79.2/node_modules/web-tree-sitter/tree-sitter.js:1:10613)
    at /var/tmp/portage/app-editors/vscode-1.79.2/work/vscode-1.79.2/node_modules/web-tree-sitter/tree-sitter.js:1:10879
    at async /var/tmp/portage/app-editors/vscode-1.79.2/work/vscode-1.79.2/node_modules/@vscode/l10n-dev/dist/main.js:254:10
    at async /var/tmp/portage/app-editors/vscode-1.79.2/work/vscode-1.79.2/node_modules/@vscode/l10n-dev/dist/main.js:243:22
[16:08:54] The following tasks did not complete: vscode-linux-x64-min

```
Logs, system info:
- [build.log.txt](https://github.com/PF4Public/gentoo-overlay/files/11886987/build.log.txt)
- [emerge.info.txt](https://github.com/PF4Public/gentoo-overlay/files/11886988/emerge.info.txt)

**Comment by PF4Public** [comment]
For your reference:
https://github.com/microsoft/vscode/issues/166265#issuecomment-1510431273
https://github.com/microsoft/vscode-l10n/issues/104
https://github.com/tree-sitter/tree-sitter-typescript/issues/244
https://github.com/tree-sitter/tree-sitter/issues/2338
https://github.com/microsoft/vscode-l10n/issues/114

I'm tired of wasting time struggling with Microsoft, so the temporary solution is [here](https://github.com/PF4Public/gentoo-overlay/issues/238#issuecomment-1605502974) and [here](https://github.com/PF4Public/gentoo-overlay/issues/238#issuecomment-1605685642).

I'll keep your issue open for some time for better visibility.

**Comment by PF4Public** [comment]
Since Microsoft does not care for this failure I've temporarily added `temp-fix` USE flag for ease of building.

**Comment by darkbasic** [comment]
With `temp-fix` It compiles "succesfully" but I see lots of errors in the npm install phase:

```
>>> Configuring source in /var/tmp/portage/app-editors/vscode-9999/work/vscode-9999 ...
 * Installing node_modules ...
yarn config v1.22.19
success Set "disable-self-update-check" to "true".
Done in 0.51s.
yarn config v1.22.19
success Set "nodedir" to "/usr/include/electron-26/node".
Done in 0.38s.
yarn install v1.22.19
$ node build/npm/preinstall.js
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@microsoft/1ds-core-js > @microsoft/applicationinsights-core-js@2.8.15" has unmet peer dependency "tslib@*".
warning " > gulp-postcss@9.0.0" has unmet peer dependency "postcss@^8.0.0".
warning " > tsec@0.2.7" has unmet peer dependency "@bazel/bazelisk@>=1.7.5".
warning " > tsec@0.2.7" has unmet peer dependency "@bazel/concatjs@>=5.3.0".
[4/4] Building fresh packages...
$ node build/npm/postinstall.js
Installing dependencies in build...
$ yarn --frozen-lockfile
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...




warning Error running install script for optional dependency: "/var/tmp/portage/app-editors/vscode-9999/work/vscode-9999/build/node_modules/tree-sitter-typescript: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /var/tmp/portage/app-editors/vscode-9999/work/vscode-9999/build/node_modules/tree-sitter-typescript
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@18.16.1 | linux | ppc64
gyp info find Python using Python version 3.11.5 found at \"/usr/bin/python3.11\"
gyp info spawn /usr/bin/python3.11
gyp info spawn args [
gyp info spawn args   '/usr/lib64/electron-26/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/var/tmp/portage/app-editors/vscode-9999/work/vscode-9999/build/node_modules/tree-sitter-typescript/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib64/electron-26/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/include/electron-26/node/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/usr/include/electron-26/node',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib64/electron-26/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/usr/include/electron-26/node/$(Configuration)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/var/tmp/portage/app-editors/vscode-9999/work/vscode-9999/build/node_modules/tree-sitter-typescript',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/var/tmp/portage/app-editors/vscode-9999/work/vscode-9999/build/node_modules/tree-sitter-typescript/build'
  CC(target) Release/obj.target/tree_sitter_typescript_binding/typescript/src/parser.o
In file included from ../typescript/src/parser.c:1:
../typescript/src/parser.c: In function ‘ts_lex_keywords’:
../typescript/src/tree_sitter/parser.h:135:8: warning: variable ‘eof’ set but not used [-Wunused-but-set-variable]
  135 |   bool eof = false;             \\\n      |        ^~~
../typescript/src/parser.c:5342:3: note: in expansion of macro ‘START_LEXER’
 5342 |   START_LEXER();
      |   ^~~~~~~~~~~
  CC(target) Release/obj.target/tree_sitter_typescript_binding/typescript/src/scanner.o
  CC(target) Release/obj.target/tree_sitter_typescript_binding/tsx/src/parser.o
In file included from ../tsx/src/parser.c:1:
../tsx/src/parser.c: In function ‘ts_lex_keywords’:
../typescript/src/tree_sitter/parser.h:135:8: warning: variable ‘eof’ set but not used [-Wunused-but-set-variable]
  135 |   bool eof = false;             \\\n      |        ^~~
../tsx/src/parser.c:5600:3: note: in expansion of macro ‘START_LEXER’
 5600 |   START_LEXER();
      |   ^~~~~~~~~~~
  CC(target) Release/obj.target/tree_sitter_typescript_binding/tsx/src/scanner.o
  CXX(target) Release/obj.target/tree_sitter_typescript_binding/bindings/node/binding.o
In file included from /usr/include/electron-26/node/include/node/v8-object.h:10,
                 from /usr/include/electron-26/node/include/node/v8-array-buffer.h:13,
                 from /usr/include/electron-26/node/include/node/v8.h:24,
                 from /usr/include/electron-26/node/include/node/node.h:79,
                 from ../bindings/node/binding.cc:2:
/usr/include/electron-26/node/include/node/v8-persistent-handle.h:245:44: warning: ‘template<class T> struct v8::CopyablePersistentTraits’ is deprecated: Use v8::Global instead [-Wdeprecated-declarations]
  245 |   using CopyablePersistent = Persistent<T, CopyablePersistentTraits<T>>;
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/electron-26/node/include/node/v8-persistent-handle.h:244:48: note: declared here
  244 | struct V8_DEPRECATED(\"Use v8::Global instead\") CopyablePersistentTraits {
      |                                                ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../nan/nan.h:178,
                 from ../bindings/node/binding.cc:3:
../../nan/nan_callbacks.h:55:23: error: ‘AccessorSignature’ is not a member of ‘v8’
   55 | typedef v8::Local<v8::AccessorSignature> Sig;
      |                       ^~~~~~~~~~~~~~~~~
../../nan/nan_callbacks.h:55:40: error: template argument 1 is invalid
   55 | typedef v8::Local<v8::AccessorSignature> Sig;
      |                                        ^
../../nan/nan.h:204:16: warning: ‘template<class T> struct v8::CopyablePersistentTraits’ is deprecated: Use v8::Global instead [-Wdeprecated-declarations]
  204 |     public v8::CopyablePersistentTraits<T> {};
      |                ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/electron-26/node/include/node/v8-persistent-handle.h:244:48: note: declared here
  244 | struct V8_DEPRECATED(\"Use v8::Global instead\") CopyablePersistentTraits {
      |                                                ^~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h: In function ‘bool Nan::IdleNotification(int)’:
../../nan/nan.h:684:63: warning: ‘bool v8::Isolate::IdleNotificationDeadline(double)’ is deprecated: Use MemoryPressureNotification() to influence the GC schedule. [-Wdeprecated-declarations]
  684 |     return v8::Isolate::GetCurrent()->IdleNotificationDeadline(
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
  685 |         idle_time_in_ms * 0.001);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~                               
In file included from /usr/include/electron-26/node/include/node/v8-initialization.h:13,
                 from /usr/include/electron-26/node/include/node/v8.h:34:
/usr/include/electron-26/node/include/node/v8-isolate.h:1297:8: note: declared here
 1297 |   bool IdleNotificationDeadline(double deadline_in_seconds);
      |        ^~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h: In function ‘void Nan::SetAccessor(v8::Local<v8::ObjectTemplate>, v8::Local<v8::String>, GetterCallback, SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, imp::Sig)’:
../../nan/nan.h:2544:19: error: no matching function for call to ‘v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>&, void (*&)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&), void (*&)(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&), v8::Local<v8::Object>&, v8::AccessControl&, v8::PropertyAttribute&, Nan::imp::Sig&)’
 2544 |   tpl->SetAccessor(
      |   ~~~~~~~~~~~~~~~~^
 2545 |       name
      |       ~~~~         
 2546 |     , getter_
      |     ~~~~~~~~~      
 2547 |     , setter_
      |     ~~~~~~~~~      
 2548 |     , obj
      |     ~~~~~          
 2549 |     , settings
      |     ~~~~~~~~~~     
 2550 |     , attribute
      |     ~~~~~~~~~~~    
 2551 |     , signature);
      |     ~~~~~~~~~~~~   
In file included from /usr/include/electron-26/node/include/node/v8-function.h:15,
                 from /usr/include/electron-26/node/include/node/v8.h:33:
/usr/include/electron-26/node/include/node/v8-template.h:809:8: note: candidate: ‘void v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>, v8::AccessorGetterCallback, v8::AccessorSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, v8::SideEffectType, v8::SideEffectType)’
  809 |   void SetAccessor(
      |        ^~~~~~~~~~~
/usr/include/electron-26/node/include/node/v8-template.h:814:22: note:   no known conversion for argument 7 from ‘Nan::imp::Sig’ {aka ‘int’} to ‘v8::SideEffectType’
  814 |       SideEffectType getter_side_effect_type = SideEffectType::kHasSideEffect,
      |       ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/electron-26/node/include/node/v8-template.h:816:8: note: candidate: ‘void v8::ObjectTemplate::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, v8::SideEffectType, v8::SideEffectType)’
  816 |   void SetAccessor(
      |        ^~~~~~~~~~~
/usr/include/electron-26/node/include/node/v8-template.h:821:22: note:   no known conversion for argument 7 from ‘Nan::imp::Sig’ {aka ‘int’} to ‘v8::SideEffectType’
  821 |       SideEffectType getter_side_effect_type = SideEffectType::kHasSideEffect,
      |       ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../bindings/node/binding.cc: At global scope:
/usr/include/electron-26/node/include/node/node.h:1010:7: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
 1010 |       (node::addon_register_func) (regfunc),                          \\\n      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/electron-26/node/include/node/node.h:1044:3: note: in expansion of macro ‘NODE_MODULE_X’
 1044 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../bindings/node/binding.cc:35:1: note: in expansion of macro ‘NODE_MODULE’
   35 | NODE_MODULE(tree_sitter_typescript_binding, Init)
      | ^~~~~~~~~~~
make: *** [tree_sitter_typescript_binding.target.mk:131: Release/obj.target/tree_sitter_typescript_binding/bindings/node/binding.o] Error 1
make: Leaving directory '/var/tmp/portage/app-editors/vscode-9999/work/vscode-9999/build/node_modules/tree-sitter-typescript/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib64/electron-26/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 6.4.14-gentoo-dist
gyp ERR! command \"/usr/lib64/electron-26/electron\" \"/usr/lib64/electron-26/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /var/tmp/portage/app-editors/vscode-9999/work/vscode-9999/build/node_modules/tree-sitter-typescript




warning Error running install script for optional dependency: "/var/tmp/portage/app-editors/vscode-9999/work/vscode-9999/build/node_modules/tree-sitter: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments: 
Directory: /var/tmp/portage/app-editors/vscode-9999/work/vscode-9999/build/node_modules/tree-sitter
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@18.16.1 | linux | ppc64
gyp info find Python using Python version 3.11.5 found at \"/usr/bin/python3.11\"
gyp info spawn /usr/bin/python3.11
gyp info spawn args [
gyp info spawn args   '/usr/lib64/electron-26/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/var/tmp/portage/app-editors/vscode-9999/work/vscode-9999/build/node_modules/tree-sitter/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib64/electron-26/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/include/electron-26/node/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/usr/include/electron-26/node',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib64/electron-26/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/usr/include/electron-26/node/$(Configuration)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/var/tmp/portage/app-editors/vscode-9999/work/vscode-9999/build/node_modules/tree-sitter',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/var/tmp/portage/app-editors/vscode-9999/work/vscode-9999/build/node_modules/tree-sitter/build'
  CC(target) Release/obj.target/tree_sitter/vendor/tree-sitter/lib/src/lib.o
rm -f Release/obj.target/tree_sitter.a Release/obj.target/tree_sitter.a.ar-file-list; mkdir -p `dirname Release/obj.target/tree_sitter.a`
ar crs Release/obj.target/tree_sitter.a @Release/obj.target/tree_sitter.a.ar-file-list
  COPY Release/tree_sitter.a
  CXX(target) Release/obj.target/tree_sitter_runtime_binding/src/binding.o
In file included from /usr/include/electron-26/node/include/node/v8-object.h:10,
                 from /usr/include/electron-26/node/include/node/v8-array-buffer.h:13,
                 from /usr/include/electron-26/node/include/node/v8.h:24,
                 from /usr/include/electron-26/node/include/node/node.h:79,
                 from ../src/binding.cc:1:
/usr/include/electron-26/node/include/node/v8-persistent-handle.h:245:44: warning: ‘template<class T> struct v8::CopyablePersistentTraits’ is deprecated: Use v8::Global instead [-Wdeprecated-declarations]
  245 |   using CopyablePersistent = Persistent<T, CopyablePersistentTraits<T>>;
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/electron-26/node/include/node/v8-persistent-handle.h:244:48: note: declared here
  244 | struct V8_DEPRECATED(\"Use v8::Global instead\") CopyablePersistentTraits {
      |                                                ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../nan/nan.h:178,
                 from ../src/./language.h:4,
                 from ../src/binding.cc:3:
../../nan/nan_callbacks.h:55:23: error: ‘AccessorSignature’ is not a member of ‘v8’
   55 | typedef v8::Local<v8::AccessorSignature> Sig;
      |                       ^~~~~~~~~~~~~~~~~
../../nan/nan_callbacks.h:55:40: error: template argument 1 is invalid
   55 | typedef v8::Local<v8::AccessorSignature> Sig;
      |                                        ^
../../nan/nan.h:204:16: warning: ‘template<class T> struct v8::CopyablePersistentTraits’ is deprecated: Use v8::Global instead [-Wdeprecated-declarations]
  204 |     public v8::CopyablePersistentTraits<T> {};
      |                ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/electron-26/node/include/node/v8-persistent-handle.h:244:48: note: declared here
  244 | struct V8_DEPRECATED(\"Use v8::Global instead\") CopyablePersistentTraits {
      |                                                ^~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h: In function ‘bool Nan::IdleNotification(int)’:
../../nan/nan.h:684:63: warning: ‘bool v8::Isolate::IdleNotificationDeadline(double)’ is deprecated: Use MemoryPressureNotification() to influence the GC schedule. [-Wdeprecated-declarations]
  684 |     return v8::Isolate::GetCurrent()->IdleNotificationDeadline(
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
  685 |         idle_time_in_ms * 0.001);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~                               
In file included from /usr/include/electron-26/node/include/node/v8-initialization.h:13,
                 from /usr/include/electron-26/node/include/node/v8.h:34:
/usr/include/electron-26/node/include/node/v8-isolate.h:1297:8: note: declared here
 1297 |   bool IdleNotificationDeadline(double deadline_in_seconds);
      |        ^~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h: In function ‘void Nan::SetAccessor(v8::Local<v8::ObjectTemplate>, v8::Local<v8::String>, GetterCallback, SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, imp::Sig)’:
../../nan/nan.h:2544:19: error: no matching function for call to ‘v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>&, void (*&)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&), void (*&)(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&), v8::Local<v8::Object>&, v8::AccessControl&, v8::PropertyAttribute&, Nan::imp::Sig&)’
 2544 |   tpl->SetAccessor(
      |   ~~~~~~~~~~~~~~~~^
 2545 |       name
      |       ~~~~         
 2546 |     , getter_
      |     ~~~~~~~~~      
 2547 |     , setter_
      |     ~~~~~~~~~      
 2548 |     , obj
      |     ~~~~~          
 2549 |     , settings
      |     ~~~~~~~~~~     
 2550 |     , attribute
      |     ~~~~~~~~~~~    
 2551 |     , signature);
      |     ~~~~~~~~~~~~   
In file included from /usr/include/electron-26/node/include/node/v8-function.h:15,
                 from /usr/include/electron-26/node/include/node/v8.h:33:
/usr/include/electron-26/node/include/node/v8-template.h:809:8: note: candidate: ‘void v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>, v8::AccessorGetterCallback, v8::AccessorSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, v8::SideEffectType, v8::SideEffectType)’
  809 |   void SetAccessor(
      |        ^~~~~~~~~~~
/usr/include/electron-26/node/include/node/v8-template.h:814:22: note:   no known conversion for argument 7 from ‘Nan::imp::Sig’ {aka ‘int’} to ‘v8::SideEffectType’
  814 |       SideEffectType getter_side_effect_type = SideEffectType::kHasSideEffect,
      |       ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/electron-26/node/include/node/v8-template.h:816:8: note: candidate: ‘void v8::ObjectTemplate::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, v8::SideEffectType, v8::SideEffectType)’
  816 |   void SetAccessor(
      |        ^~~~~~~~~~~
/usr/include/electron-26/node/include/node/v8-template.h:821:22: note:   no known conversion for argument 7 from ‘Nan::imp::Sig’ {aka ‘int’} to ‘v8::SideEffectType’
  821 |       SideEffectType getter_side_effect_type = SideEffectType::kHasSideEffect,
      |       ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc: At global scope:
/usr/include/electron-26/node/include/node/node.h:1010:7: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
 1010 |       (node::addon_register_func) (regfunc),                          \\\n      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/electron-26/node/include/node/node.h:1044:3: note: in expansion of macro ‘NODE_MODULE_X’
 1044 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/binding.cc:25:1: note: in expansion of macro ‘NODE_MODULE’
   25 | NODE_MODULE(tree_sitter_runtime_binding, InitAll)
      | ^~~~~~~~~~~
make: *** [tree_sitter_runtime_binding.target.mk:141: Release/obj.target/tree_sitter_runtime_binding/src/binding.o] Error 1
make: Leaving directory '/var/tmp/portage/app-editors/vscode-9999/work/vscode-9999/build/node_modules/tree-sitter/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib64/electron-26/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 6.4.14-gentoo-dist
gyp ERR! command \"/usr/lib64/electron-26/electron\" \"/usr/lib64/electron-26/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /var/tmp/portage/app-editors/vscode-9999/work/vscode-9999/build/node_modules/tree-sitter
Done in 45.39s.
Installing dependencies in extensions...
$ yarn --frozen-lockfile
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
$ node ./postinstall.mjs
```

Is it expected?
