### ISSUE TITLE
www-client/ungoogled-chromium-124.0.6367.155_p1: bromite_content_settings.inc not found

### ISSUE THREAD

**Issue by baconsalad** [PF4Public/gentoo-overlay#337]
I've had this issue since v123. 

```
FAILED: gen/components/content_settings/core/common/content_settings_types.mojom-module 
python3.11 ../../mojo/public/tools/mojom/mojom_parser.py --input-root ../.. --input-root gen --outpu
t-root gen --mojom-file-list=gen/components/content_settings/core/common/content_settings_types__par
ser.rsp --check-imports gen/components/content_settings/core/common/content_settings_types.build_metadata --enable-feature is_posix --enable-feature is_linux --add-module-metadata webui_module_path=/
Traceback (most recent call last):
  File "/storage/portagetmp/portage/www-client/ungoogled-chromium-124.0.6367.155_p1/work/chromium-124.0.6367.155/out/Release/../../mojo/public/tools/mojom/mojom_parser.py", line 512, in <module>
    Run(sys.argv[1:])
  File "/storage/portagetmp/portage/www-client/ungoogled-chromium-124.0.6367.155_p1/work/chromium-124.0.6367.155/out/Release/../../mojo/public/tools/mojom/mojom_parser.py", line 506, in Run
    _ParseMojoms(mojom_files, input_roots, output_root, module_roots,
  File "/storage/portagetmp/portage/www-client/ungoogled-chromium-124.0.6367.155_p1/work/chromium-124.0.6367.155/out/Release/../../mojo/public/tools/mojom/mojom_parser.py", line 321, in _ParseMojoms
    for mojom_abspath, ast in _Shard(_ParseAstHelper, map_args):
  File "/storage/portagetmp/portage/www-client/ungoogled-chromium-124.0.6367.155_p1/work/chromium-124.0.6367.155/out/Release/../../mojo/public/tools/mojom/mojom_parser.py", line 258, in _Shard
    yield target_func(*arg_tuple)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/portagetmp/portage/www-client/ungoogled-chromium-124.0.6367.155_p1/work/chromium-124.0.6367.155/out/Release/../../mojo/public/tools/mojom/mojom_parser.py", line 198, in _ParseAstHelper
    src = _ResolveInclude(mojom_abspath, input_root_paths)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/portagetmp/portage/www-client/ungoogled-chromium-124.0.6367.155_p1/work/chromium-124.0.6367.155/out/Release/../../mojo/public/tools/mojom/mojom_parser.py", line 191, in _ResolveInclude
    lines[idx] = _ResolveInclude(include_file, input_root_paths)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/portagetmp/portage/www-client/ungoogled-chromium-124.0.6367.155_p1/work/chromium-124.0.6367.155/out/Release/../../mojo/public/tools/mojom/mojom_parser.py", line 181, in _ResolveInclude
    mojom_abspath = _ResolveRelativeImportPath(mojom_abspath, input_root_paths)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/portagetmp/portage/www-client/ungoogled-chromium-124.0.6367.155_p1/work/chromium-124.0.6367.155/out/Release/../../mojo/public/tools/mojom/mojom_parser.py", line 62, in _ResolveRelativeImportPath
    raise ValueError('"%s" does not exist in any of %s' % (path, roots))
ValueError: "components/content_settings/core/common/bromite_content_settings.inc" does not exist in any of ['/storage/portagetmp/portage/www-client/ungoogled-chromium-124.0.6367.155_p1/work/chromium-124.0.6367.155', '/storage/portagetmp/portage/www-client/ungoogled-chromium-124.0.6367.155_p1/work/chromium-124.0.6367.155/out/Release/gen']
ninja: build stopped: subcommand failed.
```

**Comment by PF4Public** [comment]
It might be a race condition, try resuming with `keepwork`

**Comment by baconsalad** [comment]
Humm definately something unique to me. Tried the keepwork multiple times with no change. I also played with enabling/disabling some use flags but no difference.

`X clang cromite custom-cflags nvidia official optimize-thinlto optimize-webui proprietary-codecs pulseaudio qt5 system-crc32c system-double-conversion system-ffmpeg system-harfbuzz system-icu system-libevent system-libusb system-openh264 system-openjpeg system-png system-zstd thinlto vaapi -bluetooth -cfi -convert-dict -cups -debug -enable-driver -gtk4 -hangouts -headless -hevc -kerberos -libcxx -override-data-dir -pax-kernel -pgo -qt6 -screencast -selinux -system-abseil-cpp -system-av1 -system-brotli -system-jsoncpp -system-libvpx -system-re2 -system-snappy -system-woff2 -wayland -widevine`

I'll keep playing with it.

**Comment by PF4Public** [comment]
Let me know if you find anything. It just builds for me without issues.

**Comment by PF4Public** [comment]
@baconsalad What is your ninja version? It might be the same issue as #338, but in your case I don't have a ready solution.

**Comment by baconsalad** [comment]
Got it to compile doing what you suggested with the keepwork.

`FEATURES=keepwork emerge -v ungoogled-chromium ; FEATURES=keepwork emerge --resume`

However it crashes on load so I reverted back to v122.

```
[7279:7279:0511/224458.231642:ERROR:chrome_browser_cloud_management_controller.cc(161)] Cloud management controller initialization aborted as CBCM is not enabled. Please use the `--enable-chrome-browser-cloud-management` command line flag to enable it if you are not using the official Google Chrome build.

...

[7279:7291:0511/224458.700923:ERROR:ev_root_ca_metadata.cc(162)] Failed to decode OID: 0
/usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/optional:479: _Tp &std::_Optional_base_impl<content::DocumentAssociatedData, std::_Optional_base<content::DocumentAssociatedData>>::_M_get() [_Tp = content::DocumentAssociatedData, _Dp = std::_Optional_base<content::DocumentAssociatedData>]: Assertion 'this->_M_is_engaged()' failed.
```

**Comment by baconsalad** [comment]
and ninja is this

```
$ ninja --version
1.12.0
```

**Comment by PF4Public** [comment]
> and ninja is this

That is definitely a ninja issue.

> it crashes on load


https://github.com/PF4Public/gentoo-overlay/issues/318
