### ISSUE TITLE
www-client/ungoogled-chromium Needs TSC!!

### ISSUE THREAD

**Issue by philmb3487** [PF4Public/gentoo-overlay#379]
In order to build www-client/ungoogled-chromium, you need a net-libs/nodejs with USE flag [+npm].
It was not enabled on my system for some reason, and the build kept failing..

So the fix is to add nodejs[npm] to the ebuild.

**Comment by philmb3487** [comment]
There's still something wrong, hmm.

`FAILED: gen/chrome/browser/resources/accessibility/reading_mode_gdocs_helper/tsconfig_build_ts.json gen/chrome/browser/resources/accessibility/reading_mode_gdocs_helper/build_ts_manifest.json gen/chrome/browser/resources/accessibility/reading_mode_gdocs_helper/tsc/content.js 
python3.12 ../../tools/typescript/ts_library.py --root_gen_dir ../../../../.. --root_src_dir ../../../../../../../../ --root_dir ../../chrome/browser/resources/accessibility/reading_mode_gdocs_helper --gen_dir gen/chrome/browser/resources/accessibility/reading_mode_gdocs_helper --out_dir gen/chrome/browser/resources/accessibility/reading_mode_gdocs_helper/tsc --output_suffix build_ts --in_files content.ts --definitions ../../../../../../../../tools/typescript/definitions/chrome_event.d.ts ../../../../../../../../tools/typescript/definitions/runtime.d.ts ../../../../../../../../tools/typescript/definitions/tabs.d.ts --path_mappings /tools/typescript/definitions/\*\|../../../../../../../../tools/typescript/definitions/\*
Traceback (most recent call last):
  File "/var/tmp/portage/www-client/ungoogled-chromium-129.0.6668.70_p1/work/chromium-129.0.6668.70/out/Release/../../tools/typescript/ts_library.py", line 281, in <module>
    main(sys.argv[1:])
  File "/var/tmp/portage/www-client/ungoogled-chromium-129.0.6668.70_p1/work/chromium-129.0.6668.70/out/Release/../../tools/typescript/ts_library.py", line 227, in main
    node.RunNode([
  File "/var/tmp/portage/www-client/ungoogled-chromium-129.0.6668.70_p1/work/chromium-129.0.6668.70/third_party/node/node.py", line 38, in RunNode
    raise RuntimeError('Command \'%s\' failed\n%s' % (' '.join(cmd), err))
RuntimeError: Command '/var/tmp/portage/www-client/ungoogled-chromium-129.0.6668.70_p1/work/chromium-129.0.6668.70/third_party/node/linux/node-linux-x64/bin/node /var/tmp/portage/www-client/ungoogled-chromium-129.0.6668.70_p1/work/chromium-129.0.6668.70/third_party/node/node_modules/typescript/bin/tsc --project gen/chrome/browser/resources/accessibility/reading_mode_gdocs_helper/tsconfig_build_ts.json' failed
node:internal/modules/cjs/loader:1251
  throw err;
  ^

Error: Cannot find module '../lib/tsc.js'
Require stack:
- /var/tmp/portage/www-client/ungoogled-chromium-129.0.6668.70_p1/work/chromium-129.0.6668.70/third_party/node/node_modules/typescript/bin/tsc
    at Module._resolveFilename (node:internal/modules/cjs/loader:1248:15)
    at Module._load (node:internal/modules/cjs/loader:1074:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1339:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (/var/tmp/portage/www-client/ungoogled-chromium-129.0.6668.70_p1/work/chromium-129.0.6668.70/third_party/node/node_modules/typescript/bin/tsc:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
    at Module.load (node:internal/modules/cjs/loader:1317:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/tmp/portage/www-client/ungoogled-chromium-129.0.6668.70_p1/work/chromium-129.0.6668.70/third_party/node/node_modules/typescript/bin/tsc'
  ]
}

Node.js v22.8.0

`
$ npm
node:internal/modules/cjs/loader:1251
  throw err;
  ^

Error: Cannot find module '../lib/cli.js'
Require stack:
- /usr/lib64/node_modules/npm/bin/npm-cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1248:15)
    at Module._load (node:internal/modules/cjs/loader:1074:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1339:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (/usr/lib64/node_modules/npm/bin/npm-cli.js:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
    at Module.load (node:internal/modules/cjs/loader:1317:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/lib64/node_modules/npm/bin/npm-cli.js' ]
}

Node.js v22.8.0

``

**Comment by PF4Public** [comment]
Did it work before, at which point it started failing? Your USE flags, full build log?

**Comment by philmb3487** [comment]
Yes, turns out my 'node' is hosed. Nodejs is quite brittle, replacing /usr/bin/node with the official build, and the build continues.
Closing this issue since it's unrelated to this package.
