### ISSUE TITLE
electron-32/33 crashes with int3 SIGTRAP

### ISSUE THREAD

**Issue by Kawanaao** [PF4Public/gentoo-overlay#382]
Recently, while setting up VSCode on musl, I compiled it with Electron 32. Today, after installing a glibc system and attempting to replicate the musl steps, I discovered the issue isn't musl-specific. This problem has been reported in [Chromium](https://issues.chromium.org/issues/343086047) and [VSCode](https://github.com/microsoft/vscode/issues/213529) issues. The current Electron 32 version is broken, causing non-obvious bugs. In VSCode, it results in an int3 crash. In Webcord, the bug manifests as glitches in some settings windows. More critically, affected apps may fail to launch on the first attempt or may not launch at all. These issues don't occur with Electron 31.

**Comment by PF4Public** [comment]
32.0.1 Works fine for me, unfortunately I haven't yet updated it to the latest version, but I doubt it is as broken as you describe.

**Comment by Kawanaao** [comment]
> 32.0.1 Works fine for me, unfortunately I haven't yet updated it to the latest version, but I doubt it is as broken as you describe.

As far as I've tried to work with it, it either stops working quite chaotically under load, or applications go into fail-safe mode. After a while, they degrade to a white window, regardless of the *FLAGS set. When testing on glibc, the same thing happens. Then can you also check the misbehavior of Electron in your system?

**Comment by PF4Public** [comment]
> Then can you also check the misbehavior of Electron in your system?

I need a repro scenario. Preferably a simple one.

**Comment by Kawanaao** [comment]
> > Then can you also check the misbehavior of Electron in your system?
> 
> I need a repro scenario. Preferably a simple one.

VSCode simply closes when selecting "File" from the menu bar. There are also problems with Webcord from thegreatmcpain overlay. I replaced electron-31 with electron-32, after which the "File > Settings" window constantly blinked, and Webcord itself did not start without loading in error-ignoring mode.

I'll also try to film the errors themselves

**Comment by Kawanaao** [comment]
ehh..?

[Screencast_20241016_124017.webm](https://github.com/user-attachments/assets/aa48bad0-4020-46c2-ac6b-b3314e72cc64)

[Screencast_20241016_124753.webm](https://github.com/user-attachments/assets/cd91e432-93ec-47f3-9926-1c3dc9277165)

**Comment by PF4Public** [comment]
Have you seen #380? It looks exactly the same as your crashes. It would help if you could build electron with `-ggdb3` (as suggested on https://wiki.gentoo.org/wiki/Debugging) and obtain a complete backtrace.

**Comment by Kawanaao** [comment]
> Have you seen #380? It looks exactly the same as your crashes. It would help if you could build electron with `-ggdb3` (as suggested on https://wiki.gentoo.org/wiki/Debugging) and obtain a complete backtrace.

It seems this issue occurs with both Electron 32 and Electron 33. I might try debugging *but first, need to rebuild the system with debug info. I have disabled the register for the stack pointer*

**Comment by Kawanaao** [comment]
@PF4Public Somehow it compiled (it consumes quite a bit of memory..)

```gdb
Core was generated by `/usr/lib64/electron-33/electron --app=/usr/lib64/vscode'.
Program terminated with signal SIGTRAP, Trace/breakpoint trap.
#0  0x00006001303f3e40 in ui::Accelerator::ApplyLongFormModifiers(std::__Cr::basic_string<char16_t, std::__Cr::char_traits<char16_t>, std::__Cr::allocator<char16_t> > const&) const ()
[Current thread is 1 (Thread 0x7060e25bff00 (LWP 1259))]
(gdb) bt
#0  0x00006001303f3e40 in ui::Accelerator::ApplyLongFormModifiers(std::__Cr::basic_string<char16_t, std::__Cr::char_traits<char16_t>, std::__Cr::allocator<char16_t> > const&) const ()
#1  0x00006001303f3a26 in ui::Accelerator::GetShortcutText() const ()
#2  0x000060013105ed15 in views::MenuConfig::ShouldShowAcceleratorText(views::MenuItemView const*, std::__Cr::basic_string<char16_t, std::__Cr::char_traits<char16_t>, std::__Cr::allocator<char16_t> >*) const ()
#3  0x000060013104f528 in views::MenuItemView::CalculateDimensions() const ()
#4  0x000060013104f119 in views::MenuItemView::GetDimensions() const ()
#5  0x00006001310624b2 in views::SubmenuView::CalculatePreferredSize(views::SizeBounds const&) const ()
#6  0x00006001310675aa in views::MenuScrollViewContainer::CalculatePreferredSize(views::SizeBounds const&) const ()
#7  0x000060013105a159 in views::MenuController::CalculateBubbleMenuBounds(views::MenuItemView*, views::MenuController::MenuOpenDirection, views::MenuController::MenuOpenDirection*, ui::OwnedWindowAnchor*) ()
#8  0x0000600131059b9c in views::MenuController::OpenMenuImpl(views::MenuItemView*, bool) ()
#9  0x0000600131058458 in views::MenuController::CommitPendingSelection() ()
#10 0x0000600131052a8f in views::MenuController::SetSelection(views::MenuItemView*, int) ()
#11 0x00006001310522a0 in views::MenuController::Run(views::Widget*, views::MenuButtonController*, views::MenuItemView*, gfx::Rect const&, views::MenuAnchorPosition, bool, bool, ui::MenuSourceType, aura::Window*) ()
#12 0x00006001310605f6 in views::internal::MenuRunnerImpl::RunMenuAt(views::Widget*, views::MenuButtonController*, gfx::Rect const&, views::MenuAnchorPosition, int, ui::MenuSourceType, aura::Window*, std::__Cr::optional<gfx::RoundedCornersF>, std::__Cr::optional<std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> > >) ()
#13 0x00006001310600e8 in views::MenuRunner::RunMenuAt(views::Widget*, views::MenuButtonController*, gfx::Rect const&, views::MenuAnchorPosition, ui::MenuSourceType, aura::Window*, std::__Cr::optional<gfx::RoundedCornersF>, std::__Cr::optional<std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> > >) ()
#14 0x000060012b64d5fb in electron::MenuDelegate::RunMenu(electron::ElectronMenuModel*, views::Button*, ui::MenuSourceType) ()
#15 0x000060012b64c247 in electron::MenuBar::ButtonPressed(unsigned long, ui::Event const&) ()
#16 0x000060013102c50f in views::Button::PressedCallback::Run(ui::Event const&) ()
#17 0x000060013103b8e6 in views::MenuButtonController::Activate(ui::Event const*) ()
#18 0x000060013103ad80 in views::MenuButtonController::OnMousePressed(ui::MouseEvent const&) ()
#19 0x00006001310a7690 in views::View::ProcessMousePressed(ui::MouseEvent const&) ()
#20 0x000060013109cb32 in views::View::OnMouseEvent(ui::MouseEvent*) ()
#21 0x000060013101ff17 in ui::ScopedTargetHandler::OnEvent(ui::Event*) ()
#22 0x0000600130428946 in ui::EventDispatcher::ProcessEvent(ui::EventTarget*, ui::Event*) ()
#23 0x000060013042865b in ui::EventDispatcherDelegate::DispatchEventToTarget(ui::EventTarget*, ui::Event*) ()
#24 0x000060013042850b in ui::EventDispatcherDelegate::DispatchEvent(ui::EventTarget*, ui::Event*) ()
#25 0x00006001310b65ac in views::internal::RootView::OnMousePressed(ui::MouseEvent const&) ()
#26 0x00006001310bc329 in views::Widget::OnMouseEvent(ui::MouseEvent*) ()
#27 0x0000600130428946 in ui::EventDispatcher::ProcessEvent(ui::EventTarget*, ui::Event*) ()
#28 0x000060013042865b in ui::EventDispatcherDelegate::DispatchEventToTarget(ui::EventTarget*, ui::Event*) ()
#29 0x000060013042850b in ui::EventDispatcherDelegate::DispatchEvent(ui::EventTarget*, ui::Event*) ()
#30 0x0000600130ea90bb in ui::EventProcessor::OnEventFromSource(ui::Event*) ()
#31 0x0000600130eb5447 in aura::WindowTreeHostPlatform::DispatchEvent(ui::Event*) ()
#32 0x00006001310f932e in views::DesktopWindowTreeHostLinux::DispatchEvent(ui::Event*) ()
#33 0x000060013042eff7 in ui::DispatchEventFromNativeUiEvent(ui::Event* const&, base::OnceCallback<void (ui::Event*)>) ()
#34 0x000060012bff8e99 in ui::WaylandWindow::DispatchEvent(ui::Event* const&) ()
#35 0x00006001303f98dd in ui::PlatformEventSource::DispatchEvent(ui::Event*) ()
#36 0x000060012bfd1783 in ui::WaylandEventSource::SetTargetAndDispatchEvent(ui::Event*, ui::EventTarget*) ()
#37 0x000060012bfcca7f in ui::WaylandEventSource::OnPointerButtonEvent(ui::EventType, int, base::TimeTicks, ui::WaylandWindow*, wl::EventDispatchPolicy, bool, bool) ()
#38 0x000060012bfe8b8d in ui::WaylandPointer::OnButton(void*, wl_pointer*, unsigned int, unsigned int, unsigned int, unsigned int) ()
#39 0x00007060eff3751e in ??? () at /usr/lib64/libffi.so.8
#40 0x00007060eff3c5a6 in ??? () at /usr/lib64/libffi.so.8
#41 0x00007060eff3c1b4 in ffi_call () at /usr/lib64/libffi.so.8
#42 0x000060012bf8c60c in wl_closure_invoke ()
--Type <RET> for more, q to quit, c to continue without paging--
#43 0x000060012bf89f39 in dispatch_event ()
#44 0x000060012bf89d0b in wl_display_dispatch_queue_pending ()
#45 0x000060012c02ea9b in ui::WaylandEventWatcher::WlDisplayDispatchPendingQueue() ()
#46 0x000060012c02f37f in ui::(anonymous namespace)::WatchSourceDispatch(_GSource*, int (*)(void*), void*) ()
#47 0x00007060f0d6bdf3 in ??? () at /usr/lib64/libglib-2.0.so.0
#48 0x00007060f0d6c6d6 in ??? () at /usr/lib64/libglib-2.0.so.0
#49 0x00007060f0d6c83f in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#50 0x000060012f484acf in base::MessagePumpGlib::Run(base::MessagePump::Delegate*) ()
#51 0x000060012f421d41 in base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) ()
#52 0x000060012f3e7ffc in base::RunLoop::Run(base::Location const&) ()
#53 0x000060012dcca456 in content::BrowserMainLoop::RunMainMessageLoop() ()
#54 0x000060012dccbd52 in content::BrowserMainRunnerImpl::Run() ()
#55 0x000060012dcc71c3 in content::BrowserMain(content::MainFunctionParams) ()
#56 0x000060012b803acb in content::RunBrowserProcessMain(content::MainFunctionParams, content::ContentMainDelegate*) ()
#57 0x000060012b80424d in content::ContentMainRunnerImpl::RunBrowser(content::MainFunctionParams, bool) ()
#58 0x000060012b802e6e in content::ContentMainRunnerImpl::Run() ()
#59 0x000060012b801382 in content::RunContentProcess(content::ContentMainParams, content::ContentMainRunner*) ()
#60 0x000060012b801922 in content::ContentMain(content::ContentMainParams) ()
#61 0x000060012b432b75 in main ()
(gdb) 
```

**Comment by Kawanaao** [comment]
It looks like the bug has already reached upstream

https://github.com/microsoft/vscode/issues/230604
https://github.com/electron/electron/pull/44341

Maybe it's worth backporting it to electron-(32/33)?
