### ISSUE TITLE
www-client/ungoogled-chromium-92.0.4515.131-r2: python 3.10 is not supported

### ISSUE THREAD

**Issue by imrebuild** [PF4Public/gentoo-overlay#95]
Got error while building ungoogled-chromium with python 3.10:
```
Traceback (most recent call last):
  File "/var/tmp/portage/www-client/ungoogled-chromium-92.0.4515.131-r2/work/chromium-92.0.4515.131/out/Release/../../v8/third_party/inspector_protocol/code_generator.py", line 702, in <module>
    main()
  File "/var/tmp/portage/www-client/ungoogled-chromium-92.0.4515.131-r2/work/chromium-92.0.4515.131/out/Release/../../v8/third_party/inspector_protocol/code_generator.py", line 584, in main
    jinja_env = initialize_jinja_env(jinja_dir, config.protocol.output, config)
  File "/var/tmp/portage/www-client/ungoogled-chromium-92.0.4515.131-r2/work/chromium-92.0.4515.131/out/Release/../../v8/third_party/inspector_protocol/code_generator.py", line 190, in initialize_jinja_env
    import jinja2
  File "/var/tmp/portage/www-client/ungoogled-chromium-92.0.4515.131-r2/work/chromium-92.0.4515.131/third_party/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/var/tmp/portage/www-client/ungoogled-chromium-92.0.4515.131-r2/work/chromium-92.0.4515.131/third_party/jinja2/environment.py", line 16, in <module>
    from jinja2.defaults import BLOCK_START_STRING, \
  File "/var/tmp/portage/www-client/ungoogled-chromium-92.0.4515.131-r2/work/chromium-92.0.4515.131/third_party/jinja2/defaults.py", line 32, in <module>
    from jinja2.tests import TESTS as DEFAULT_TESTS
  File "/var/tmp/portage/www-client/ungoogled-chromium-92.0.4515.131-r2/work/chromium-92.0.4515.131/third_party/jinja2/tests.py", line 13, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```
Running `from collections import Mapping` on python 3.9 shows:
```
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
```

We may need to patch the file or remove 3.10 from `PYTHON_COMPAT`.

**Comment by PF4Public** [comment]
Interesting! Sorry, my bad.

**Comment by perfect7gentleman** [comment]
patch - https://src.fedoraproject.org/rpms/chromium/blob/rawhide/f/chromium-92.0.4515.107-py3-fixes.patch

**Comment by PF4Public** [comment]
@perfect7gentleman By the look of this patch, looks like it is sufficient to just apply it, as it checks python version itself, I'll add this patch to the ebuild a bit later.
